### ISSUE TITLE
Screenshot/photo of the gantt chart

### ISSUE THREAD

**Issue by anjanaramkumar** [Cogulator/Cogulator#1]
Hello,

   When i have only the Motor Operator with Hands operators and if i try to take a picture, the gantt chart stored has only the perceptual and cognitive operators and i dont see my Motor operators at all.
![gantt-chart](https://cloud.githubusercontent.com/assets/17180297/12980477/dabf51f2-d0dc-11e5-8b98-d18694673906.png) Please see the image. I could see only a blank gantt chart.

My second question : How can i visualize two models in the same chart e.g: below one another? One complete KLM and CPM model in the same visualization but as two different workflows one below the other and not as a continuation?

**Comment by Tapestes** [comment]
I'll take a look at the screenshot issue shortly.  There is no way to view multiple models simultaneously in Cogulator.

**Comment by Tapestes** [comment]
I'm able to reproduce the screenshot issue.  I'll find a fix and push it out ASAP.

**Comment by anjanaramkumar** [comment]
Thank you...

**Comment by Tapestes** [comment]
Alright, just released an update.  Next time you open Cogulator it should give you the option to update to v1.2, which has the fix in it.  Otherwise, just head over to the releases and download the latest version (https://github.com/Cogulator/Cogulator/releases/tag/v1.2).  

Cheers.
