### ISSUE TITLE
Cannot install on latest version of AIR?

### ISSUE THREAD

**Issue by lucasrizoli** [Cogulator/Cogulator#11]
I have attempted to run and install the past half-dozen releases of Cogulator on Air 28.0, but keep getting a n error: "The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author." Any idea what to do?

**Comment by lucasrizoli** [comment]
![capture 1](https://user-images.githubusercontent.com/550536/37309310-eb1dda8c-2616-11e8-99c9-a9a3101cdf0d.PNG)

**Comment by Tapestes** [comment]
Good news... I'm seeing the same issue.  It runs on my machine with 28, but if I try and reinstall, I get the damaged message.  I'll build a release targeting 28, I push that in the next day or two.  When I do, I'll post an update here.

**Comment by Tapestes** [comment]
OK... this looks like it might be a self-signed cert issue.  I'm working with my employer to get an official cert, but that's taking some time.  At any rate, I created a new release with a new self signed cert.  If you have an older version of Cogulator installed, uninstall it.  Then, try this prerelease...
https://github.com/Cogulator/Cogulator/releases/tag/v3.15

Let me know how that works out for you, and I'll make it a production ready release.  Thanks.

**Comment by lucasrizoli** [comment]
Excellent. Appears to have solved the issue! Thanks!
