### ISSUE TITLE
Installation file seems broken

### ISSUE THREAD

**Issue by c06n** [Cogulator/Cogulator#12]
Hi,

unfortunately I cannot install version 3.6. An error keeps occuring: 

"Unfortunately an error occured. The application could not be installed, since the installation file is damaged. ..."

![error_msg](https://user-images.githubusercontent.com/1955472/37340459-81066e54-26be-11e8-8c2c-0284d79e7ef1.png)

OS: Win 7; Adobe Air: Version 29.0

It would be great to try the updated version.

**Comment by Tapestes** [comment]
Working on resolving a cert issue.  Until the permanent solution is in place...
- If you have an older version of Cogulator installed, uninstall it
- Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15

If that doesn't work for you, give me a shout.
