### ISSUE TITLE
Installer File

### ISSUE THREAD

**Issue by eliciadurtnall** [Cogulator/Cogulator#13]
I have run into an issue with installing this application. Attached is a screenshot of the error message I am getting. 
<img width="485" alt="installer_file_damaged" src="https://user-images.githubusercontent.com/32488709/37924702-a00dfa14-3100-11e8-98ad-6f30d83f0f04.png">

**Comment by Tapestes** [comment]
Working on resolving a cert issue. Until the permanent solution is in place...
- If you have an older version of Cogulator installed, uninstall it
- Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15
If that doesn't work for you, give me a shout.
