### ISSUE TITLE
damaged cogulator installer file

### ISSUE THREAD

**Issue by jboyd7** [Cogulator/Cogulator#14]
tried to install coagulator and got this message

The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author.

**Comment by Tapestes** [comment]
Working on resolving a cert issue. Until the permanent solution is in place...

- If you have an older version of Cogulator installed, uninstall it
- Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15

If that doesn't work for you, give me a shout.

**Comment by jboyd7** [comment]
Thanks Steve.  I am out at the Dr now but will try it when I get back.   Looks very interesting.   And my comment about cognitive loading for use by UAS is just me thinking out loud.


V/R

Joe

Joe Boyd
Systems Engineer-Lead
The MITRE Corporation

703-983-3360 (o)
773-960-0663 (c)

jboyd@mitre.org
joe.boyd.CTR@navy.mil
joseph.m.boyd.ctr@navy.smil.mil

Sent from mobile device-no electronic signature

**Comment by jboyd7** [comment]
That loaded/worked. I’ll mess with it when I am back from vacation.

Thanks again Steve



V/R

Joe

Joe Boyd
Systems Engineer-Lead
The MITRE Corporation

703-983-3360 (o)
773-960-0663 (c)

jboyd@mitre.org<mailto:jboyd@mitre.org>
joe.boyd.CTR@navy.mil<mailto:joe.boyd.CTR@navy.mil>
joseph.m.boyd.ctr@navy.smil.mil<mailto:joseph.m.boyd.ctr@navy.smil.mil>
