### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by animeshUX** [Cogulator/Cogulator#15]
<img width="487" alt="screen shot 2018-03-30 at 10 26 48 am" src="https://user-images.githubusercontent.com/19954136/38146929-fa253bb4-3404-11e8-93a5-55db026dcc2b.png">

**Comment by Tapestes** [comment]
Working on resolving a cert issue. Until the permanent solution is in place...

- If you have an older version of Cogulator installed, uninstall it
- Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15

If that doesn't work for you, give me a shout.

**Comment by animeshUX** [comment]
Thanks, the beta is working.
