### ISSUE TITLE
Damaged installer file?

### ISSUE THREAD

**Issue by cprphd** [Cogulator/Cogulator#16]
Upon trying to install Cogulator tonight, I received the error message "Sorry, an error has occured.  The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author."  (screenshot below)

Got a new version?  

I tested my Adobe AIR installation with another AIR application, and it worked fine.  ~C

![screen shot 2018-04-04 at 9 42 27 pm](https://user-images.githubusercontent.com/38093652/38347946-7d190652-3853-11e8-862e-029006738663.png)

**Comment by Tapestes** [comment]
Working on resolving a cert issue. Until the permanent solution is in place...

- If you have an older version of Cogulator installed, uninstall it
- Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15

If that doesn't work for you, give me a shout.
