### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by ksednew** [Cogulator/Cogulator#17]
Hello! I just tried to download coagulator (after downloading Adobe AIR), and received this error: "The application could not be installed because the installer file is damaged. Try obtaining a new installer file from the application author." Thank you.

**Comment by Tapestes** [comment]
Working on resolving a cert issue. Until the permanent solution is in place...
. If you have an older version of Cogulator installed, uninstall it
. Install this release https://github.com/Cogulator/Cogulator/releases/tag/v3.15
If that doesn't work for you, give me a shout.

**Comment by ksednew** [comment]
Thank you!!
