### ISSUE TITLE
text for references with targets not showing up properly on Gantt chart

### ISSUE THREAD

**Issue by michellemichaels** [Cogulator/Cogulator#24]
Hi cogulator team, my team has been using your tool and find it great. However, one bug: when I use reference a goal that has a target, the <target> text for that reference doesn't appear on the Gantt chart. However, the text does show up properly on hover. Here's an example: 
<img width="1073" alt="Screen Shot 2019-09-17 at 4 22 19 PM" src="https://user-images.githubusercontent.com/7843175/65051113-cebf9900-d968-11e9-8a8a-ade2e7fe62fd.png">

I can see that when I write out everything manually it works fine: 

<img width="1330" alt="Screen Shot 2019-09-17 at 4 35 31 PM" src="https://user-images.githubusercontent.com/7843175/65051328-3970d480-d969-11e9-9424-b9fef7bb9b4d.png">

Or writing it out with subgoals manually it's more correct, but beginning of the Gantt still looks wrong:
 
<img width="1290" alt="Screen Shot 2019-09-17 at 4 39 56 PM" src="https://user-images.githubusercontent.com/7843175/65051696-d59adb80-d969-11e9-8bc9-354df15c47a6.png">

Here's the example text if you want to verify:

EXAMPLE 1
goal:  navigate to new Indicator form
.hands to mouse
.goal: point click <left nav>
..Look at <left nav>
..Point to <left nav>﻿ (1000 milliseconds) *Fitts Law Point Estimate
..Cognitive_processor verify cursor over <left nav>
..Click mouse
.hands to keyboard
.type Indicators
. hands to mouse
.@goal: point click <Indicators / Automated indicators> 
.@goal: point click <New button>

EXAMPLE 2
goal:  navigate to new Indicator form
.Look at <left nav>
.Point to <left nav>﻿ (1000 milliseconds) *Fitts Law Point Estimate
.Cognitive_processor verify cursor over <left nav>
.Click mouse
.hands to keyboard
.type Indicators
. hands to mouse
.Look at <Indicators / Automated indicators> 
.Point to <Indicators / Automated indicators>  (1000 milliseconds) *Fitts Law Point Estimate
.Cognitive_processor verify cursor over <Indicators / Automated indicators> 
.Click mouse
.Look at <New button>
.Point to <New button>  (1000 milliseconds) *Fitts Law Point Estimate
.Cognitive_processor verify cursor over <New button>
.Click mouse

EXAMPLE 3
goal:  navigate to new Indicator form
.goal: point click left nav
..Look at <left nav>
..Point to <left nav>﻿ (1000 milliseconds) *Fitts Law Point Estimate
..Cognitive_processor verify cursor over <left nav>
..Click mouse
.hands to keyboard
.type Indicators
. hands to mouse
.goal: point click automated indicators
..Look at <Indicators / Automated indicators> 
..Point to <Indicators / Automated indicators>  (1000 milliseconds) *Fitts Law Point Estimate
..Cognitive_processor verify cursor over <Indicators / Automated indicators> 
..Click mouse
.goal:  point click new button
..Look at <New button>
..Point to <New button>  (1000 milliseconds) *Fitts Law Point Estimate
..Cognitive_processor verify cursor over <New button>
..Click mouse

**Comment by Tapestes** [comment]
Michelle... sorry it took so long to get back to you.  Didn't see a notification on this issue.  Let me see what I can figure out...

**Comment by Tapestes** [comment]
Found the fix.  Committed to the repo, but I need to make a couple o' new releases.  As soon as I do that (hopefully tomorrow), I'll close this out.

**Comment by Tapestes** [comment]
Just released v4.1.2 with the fix.  Let me know if you run into any issues.
