### ISSUE TITLE
Cogulator Download Link 404 Error

### ISSUE THREAD

**Issue by DaveHullinger** [Cogulator/Cogulator#3]
Hello, I'm trying to download Cogulator as I am taking the workshop next week at HFES and I get a 404 Error, Page not found when I click on the Cogulator download link. I installed the Adobe Air without a problem.

Regards,

Dave Hullinger

**Comment by Tapestes** [comment]
Dave,

I managed to forget to attach the binary to the release.  Binary is up and link appears to be working now.  

Cheers,

Steven

**Comment by DaveHullinger** [comment]
Thanks!

Dave
