### ISSUE TITLE
Permission error "Could not create file"

### ISSUE THREAD

**Issue by enginpost** [Cogulator/Cogulator#34]
I am using Windows 11 and if I attempt to create a new model is shows the following error...

![image](https://user-images.githubusercontent.com/641069/176305032-0cc9c163-4164-4140-9d37-bf542b340da1.png)

It wants to save to my Documents folder and my Documents folder is setup to use OneDrive, which could be the issue. I have not had a permission issue with other software struggling to write files to OneDrive or Documents.

Can we change where the system wants to save files?

**Comment by Tapestes** [comment]
The error message you're seeing is spurious.  This is a known issue, and I should have a updated version by the end of the week that'll take care of that bug.  In any case, when you hit "OK" it should create the file without any problem.

Currently, Cogulator will only read and save to the cogulator folder in your documents directory.  At some point, we can look at allowing the user to set which directory they want to read from.

**Comment by Tapestes** [comment]
Issue should be resolved in the latest release, which is v4.3.7. 
[https://github.com/Cogulator/Cogulator/releases/tag/v4.3.7](https://github.com/Cogulator/Cogulator/releases/tag/v4.3.7)
