### ISSUE TITLE
A JavaScript Error occured in the main process

### ISSUE THREAD

**Issue by andriisydor** [Cogulator/Cogulator#38]
![image](https://user-images.githubusercontent.com/91389024/191808154-1e86f131-bab7-4da8-a25f-1c931535cbd6.png)

Hello! This is what happend when I open cogulator after installation.

**Comment by Tapestes** [comment]
@andriisydor, just saw this message.  I'll dig in a bit and see if I can't recreate.  Couple o' questions:
- Did you install the latest version (Beta 4.1.1)
- After you dismiss the notification, does everything run as expected?

**Comment by andriisydor** [comment]
@Tapestes
1) The app was installed from the site so I am not entirely sure
2) After I had closed this error window, I saw an almost blank Cogulator window. It wasn't working correctly because this error would occur each time I pressed any button. After a few clicks app window freezes.

**Comment by Tapestes** [comment]
@andriisydor I think there are probably two issues, but hopefully resolving the first one (the error message you got) will help us resolve the first.  I'll have a new release out by the end of the day Monday with a fix for the issue you saw.

**Comment by Tapestes** [comment]
@andriisydor, just released v4.2.2 which should address your issue.  You can download [here](https://github.com/Cogulator/Cogulator/releases/tag/v4.4.2).  If you run into any other issues, don't hesitate to reach out.
