### ISSUE TITLE
Not running in adobe flash

### ISSUE THREAD

**Issue by Nidhin009** [Cogulator/Cogulator#5]
Hi Cogulator team,

I downloaded and opened the project in adobe flash. Then I pressed Alt+Enter. It gave an error in AppUpdater.cs file in 

private static function onUpdate(evt:UpdateEvent):void {
			updater.checkNow();
		}

**Comment by Tapestes** [comment]
This is Adobe’s terrible way of letting you know you need to point to the application updater UI in your publication settings.  To do that…
- In Animate, with the cogulator.fla file open and in focus, select File > Publish Settings
- As in the image below, hit the wrench next to ActionScript 3.0
- In the Advanced ActionScript 3.0 Settings window, hit the Browse to .SWC button (circled in the image on the right)
- Select the app updater UI .swc file in the Air SDK (on my Mac, it’s located at Applications/Adobe Animate CC 2015.2/AIR21.0/frameworks/lib/air)
 
More info here…
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/air/update/ApplicationUpdater.html
 
![unknown](https://cloud.githubusercontent.com/assets/6743048/26727010/1fc85dda-4773-11e7-9492-d2503546adcf.png)

You'll also need to install some fonts, and get the items in the library pointing to them.  Source Code Pro, Lato, & Arvo are all freely available on Google Fonts.  I've attached a modification of Lato that you'll need called CoguLato. 
[CoguLato.ttf.zip](https://github.com/Cogulator/Cogulator/files/1047739/CoguLato.ttf.zip)

Hope that helps,
 
s
