### ISSUE TITLE
Edit/delete option for custom methods

### ISSUE THREAD

**Issue by Amal098** [Cogulator/Cogulator#8]
In the current version, there is no way to edit or delete a custom made method.

**Comment by Tapestes** [comment]
I’ve been meaning to add a way to delete a custom method.  When I get back
to my desk I’ll see what I can do about that.  Editing in app is probably
not going to happen soon, however you can edit a method outside the app.
Navigate to your documents folder, and look inside the cogulator/methods
folder.  You’ll see all your methods in that folder, saved as .goms files.
These .goms files are just text files, and can be modified in any text
editor.

**Comment by Tapestes** [comment]
Added ability to delete methods from within Cogulator in v3.1.  Available now.  Cheers.
